# Практикум по методу Гаусса

Переименуйте данный файл в соответствии с вашим логином. По окончании работы сохраните полученный файл (в формате \*.ipynb) в папку `Contest`

Результат работы всех заданий должен быть выведен на экран.

В большинстве заданий ответ предполагает написание 5-10 строк кода, однако вы можете решить их так, как вам удобнее.

В нескольких заданиях код может быть уже написан. Изучите, как он работает.

In [20]:
import numpy as np

#### 1. Для следующей системы уравнений $$\begin{cases}
0.0003x + 3y = 2.0001 \\
x + y = 1 \end{cases}$$ постройте расширенную матрицу $\mathbf{A}$, содержащую коэффициенты уравнений и вектор свободных членов (★☆☆)

In [21]:
A = np.array([[0.0003, 3, 2.0001], [1, 1, 1]])
print(A)

[[3.0000e-04 3.0000e+00 2.0001e+00]
 [1.0000e+00 1.0000e+00 1.0000e+00]]


#### 2. Преобразуйте матрицу $\mathbf{A}$, исключив переменные методом Гаусса. Для этого домножьте первую строчку матрицы на коэффициент $c = -\frac{a_{21}}{a_{11}}$ , сложите со второй строчкой и поменяйте вторую строчку на получившийся результат.

In [22]:
c = -A[1, 0] / A[0, 0]
print(f"Коэффициент c = -a21/a11 = -{A[1,0]}/{A[0,0]} = {c}")
print()

first_row = A[0].copy()
A[1] = c * A[0] + A[1]

print("Матрица после преобразования")
print(A)

Коэффициент c = -a21/a11 = -1.0/0.0003 = -3333.3333333333335

Матрица после преобразования
[[ 3.0000e-04  3.0000e+00  2.0001e+00]
 [ 0.0000e+00 -9.9990e+03 -6.6660e+03]]


#### Найдите неизвестные $x_1$ и $x_2$. Сравните их с точным решением $\left(\frac13,\frac23\right)$, объясните различие. (★☆☆)

In [23]:
y = A[1, 2] / A[1, 1]
x = (A[0, 2] - A[0, 1] * y) / A[0, 0]
print(f"x = {x}, y = {y}")

x = 0.3333333333340368, y = 0.6666666666666667


#### 3. Объедините ранее написанный код в функцию `Gauss2x2` для решения системы $2\times 2$. (★☆☆)

In [24]:
def Gauss2x2(A):
    A = A.copy().astype(float)
    c = -A[1, 0] / A[0, 0]
    A[1] = c * A[0] + A[1]
    x2 = A[1, 2] / A[1, 1]
    x1 = (A[0, 2] - A[0, 1] * x2) / A[0, 0]
    return x1, x2
    
x, y = Gauss2x2(A)
print(f"x = {x}, y = {y}")

x = 0.3333333333340368, y = 0.6666666666666667


#### 4. С использованием ранее написанной функции `Gauss2x2`, решите систему уравнений из задания 1, поменяв местами 1-ю и 2-ю строки матрицы. Объясните различие. (★☆☆)

In [ ]:
def Gauss2x2(A):
    A = A.copy().astype(float)
    c = -A[1, 0] / A[0, 0]
    A[1] = c * A[0] + A[1]
    x2 = A[1, 2] / A[1, 1]
    x1 = (A[0, 2] - A[0, 1] * x2) / A[0, 0]
    return x1, x2

A = np.array([[0.0003, 3, 2.0001], [1, 1, 1]])
A_swapped = np.array([[1, 1, 1], [0.0003, 3, 2.0001]])

x1, x2 = Gauss2x2(A)
x1_swapped, x2_swapped = Gauss2x2(A_swapped)

print(f"исходный: x = {x1}, y = {x2}")
print(f"переставлены: x = {x1_swapped}, y = {x2_swapped}")
print(f"Точное решение: x = {1/3}, y = {2/3}")

исходный: x = 0.3333333333340368, y = 0.6666666666666667
переставлены: x = 0.33333333333333326, y = 0.6666666666666667
Точное решение: x = 0.3333333333333333, y = 0.6666666666666666


#### 5*. С использованием ранее написанной функции `Gauss2x2`, для матрицы коэффициентов $$\mathbf{A}=\begin{pmatrix} 0.0003 & 3.0\\ 1.0 & 1.0\end{pmatrix}$$ найдите обратную матрицу $\mathbf{A^{-1}}$. Покажите, что найденная матрица действительно является обратной матрице $\mathbf{A}$. (★☆☆)

In [32]:
def Gauss2x2(A):
    A = A.copy().astype(float)
    c = -A[1, 0] / A[0, 0]
    A[1] = c * A[0] + A[1]
    x2 = A[1, 2] / A[1, 1]
    x1 = (A[0, 2] - A[0, 1] * x2) / A[0, 0]
    return x1, x2

A = np.array([[0.0003, 3.0], [1.0, 1.0]])

I = np.eye(2)

inv_col1 = Gauss2x2(np.column_stack([A, I[:, 0]]))
inv_col2 = Gauss2x2(np.column_stack([A, I[:, 1]]))

A_inv = np.column_stack([inv_col1, inv_col2])

print ("Обратная матрица A^-1:")
print (A_inv)

print ("Проверим что полученная матрица является обратной")
print (A@A_inv)
print ("Главня диагональ единичная, всё остальное равно нулю => получили единичную матрицу при умножении")

Обратная матрица A^-1:
[[-3.33366670e-01  1.00010001e+00]
 [ 3.33366670e-01 -1.00010001e-04]]
Проверим что полученная матрица является обратной
[[ 1.00000000e+00  1.35525272e-20]
 [-4.63851180e-13  1.00000000e+00]]
Главня диагональ единичная, всё остальное равно нулю => получили единичную матрицу при умножении


#### 6. Рассмотрим решение системы линейных уравнений для нахождения коэффициентов уравнения химической реакции на примере реакции горения октана, $\require{mhchem} \ce{C8H18}$. Нам нужно найти неизвестные коэффициенты  $x_1$, $x_2$, $x_3$, и $x_4$ в следующем уравнении: $$x_1\ce{C8H18} + x_2\ce{O2 ->} x_3\ce{CO2} + x_4\ce{H2O}$$ Для этих неизвестных можно записать 3 уравнения из условий материального баланса по $\ce{C}$, $\ce{H}$ и $\ce{O}$ соответственно. Например, 1-е уравнение: $$8x_1 - x_3 = 0$$ (Остальные уравнения составьте самостоятельно.) Эта система недоопределена (3 уравнения и 4 неизвестных). Однако, известно, что коэффициенты уравнения реакции определены с точностью до постоянного множителя, поэтому, полученную систему можно дополнить, например, 4-м уравнением $x_1=1$. Теперь система может быть решена. Для этой системы задайте матрицу коэффициентов $\mathbf{A}$ и вектор свободных членов $\mathbf{b}$. Решите полученную систему, используя функцию `solve()` из модуля `numpy.linalg`.

In [ ]:
# C: 8x1 - x3 = 0
# H: 18x1 - 2x4 = 0
# O: 2x2 - 2x3 - x4 = 0
# x1 = 1

A = np.array([
    [8, 0, -1, 0],
    [18, 0, 0, -2],
    [0, 2, -2, -1],
    [1, 0, 0, 0]
])

b = np.array([0, 0, 0, 1])

x = np.linalg.solve(A, b)
print(x)

[ 1.  12.5  8.   9. ]


#### Найдите натуральное число, умножив на которое вектор коэффициентов $\mathbf{x}$, получится вектор, содержащий только целые числа (с точностью до ошибок округления). Выведите полученное целочисленное решение. (★☆☆)

In [27]:
A = np.array([[8, 0, -1, 0], [18, 0, 0, -2], [0, 2, -2, -1], [1, 0, 0, 0]])
b = np.array([0, 0, 0, 1])
x = np.linalg.solve(A, b)

def find_multiplier(x):
    for m in range(1, 1000):
        if np.allclose(x * m, np.round(x * m)):
            return m
    return None

m = find_multiplier(x)
integer_solution = (x * m).astype(int)
print(integer_solution)

[ 2 25 16 18]


#### 7*. Аналогично предыдущему заданию, составьте и решите систему уравнений для нахождения коэффициентов реакции окисления гексациано-хром (II) гексамочевины-хрома (III) перманганат-ионом в кислой среде: $$\ce{[Cr(N2H4CO)6]4[Cr(CN)6]3 + MnO4- + H+ -> Cr2O7^2- + Mn^2+ + CO2 + NO3- + H2O}$$ (для реакций с участием ионов в дополнение к уравнениям материального баланса необходимо также записать уравнение ионного баланса: суммы зарядов в левой и правой частях уравнения должны быть одинаковы). Как и в предыдущем задании, найдите целочисленные коэффициенты.(★☆☆)

In [28]:
A = np.array([
    [7, 0, 0, -2, 0, 0, 0, 0],
    [42, 0, 0, 0, 0, -1, 0, 0],
    [66, 0, 0, 0, 0, 0, -1, 0],
    [96, 0, 1, 0, 0, 0, 0, -2],
    [24, 4, 0, -7, 0, -2, -3, -1],
    [0, 1, 0, 0, -1, 0, 0, 0],
    [3, -1, 1, 2, -2, 0, 1, 0],
    [1, 0, 0, 0, 0, 0, 0, 0]   # x1 = 1
])

b = np.array([0, 0, 0, 0, 0, 0, 0, 1])

x = np.linalg.solve(A, b)

def find_multiplier(x):
    for m in range(1, 1000):
        if np.allclose(x * m, np.round(x * m)):
            return m
    return None

m = find_multiplier(x)
integer_solution = np.round(x * m).astype(int)
print("коэффициенты:", integer_solution)

коэффициенты: [  2 234 550   7 234  84 132 371]
