#### <p style='text-align: justify;'>1. Напишите функцию `dist(X1, X2)`, которая возвращает расстояние между двумя точками, заданными векторами $X_1 = (x_1, y_1, z_1)$ и $X_2 = (x_2, y_2, z_2)$ (вектора являются массивами `numpy`).

In [1]:
import numpy as np

def dist(X1, X2):
    d = np.sqrt(sum((X2 - X1) ** 2))
    return d   

#### <p style='text-align: justify;'>Проверьте написанную вами функцию: расстояние между точками $A_1$ и $A_2$ составляет $1.534$.

In [2]:
A1 =  np.array([-0.4983977,  0.4963288, 0.0000000])
A2 =  np.array([ 0.6327199, -0.5398802, 0.0000000])

print(dist(A1, A2))

1.5340000380413163


#### <p style='text-align: justify;'>2. Одним из распространённых способов хранения информации о трёхмерной структуре молекулы являются файлы в [<i>XYZ-формате</i>](https://en.wikipedia.org/wiki/XYZ_file_format). Это файлы в текстовом формате, в которых первая строка содержит одно целое число $N$ — число атомов в молекуле, далее — строка комментария (обычно она содержит название соединения) и далее — $N$ строк, содержащих символ химического элемента и $x$, $y$, $z$-координаты атома.<br> Используя функцию `np.loadtxt()` считайте в массив `coords` координаты атомов в молекуле 1-фторпропана. Структура молекулы содержится в файле `share/1-Fluoropropane.xyz`. Выведите на печать $N$ — число атомов в молекуле и массив `coords`.

In [3]:
coords = np.loadtxt('share/1-Fluoropropane.xyz', float, skiprows = 2, usecols = (1, 2, 3))
N = len(coords)
print(coords)
print(N)

[[-0.4983977  0.4963288  0.       ]
 [ 0.6327199 -0.5398802  0.       ]
 [ 1.9994337  0.1567181  0.       ]
 [-1.7324325 -0.1191378  0.       ]
 [ 0.5525959 -1.1716898  0.8895127]
 [ 0.5525959 -1.1716898 -0.8895127]
 [-0.429092   1.1293539  0.8895571]
 [-0.429092   1.1293539 -0.8895571]
 [ 2.1016546  0.785268   0.8895571]
 [ 2.8013218 -0.587467   0.       ]
 [ 2.1016546  0.785268  -0.8895571]]
11


#### <p style='text-align: justify;'>3. Структурную формулу химического соединения можно хранить в виде матрицы смежности. Элемент такой матрицы $a_{ij}$ равен порядку связи $i$-го и $j$-го атомов (если атомы не связаны — $0$, на диагонали — $0$). Нумерация атомов в молекуле произвольная. Например, для муравьиной кислоты матрица смежности может выглядеть следующим образом: <br><br><center><img src="https://lk.challenges2024.ru/visualization/adjacency-matrix.png" width="30%"></center><br> Для построения матрицы смежности можно использовать следующий упрощённый алгоритм: пренебрегаем кратными связями, попарно вычисляем расстояния между атомами, и если расстояние между $i$-м и $j$-м атомом не превышает $1.6$, то устанвливаем $a_{ij} = 1$, иначе $a_{ij} = 0$. Создайте и выведите на печать массив, содержащий матрицу смежности для 1-фторпропана.

In [4]:
A = np.zeros((11, 11), int)
for i in range(N):
    for j in range(N):
        if 0 < dist(coords[i], coords[j]) <= 1.6:
            A[i][j] = 1

print(A)

[[0 1 0 1 0 0 1 1 0 0 0]
 [1 0 1 0 1 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 1 1 1]
 [1 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0]]


In [ ]:
atoms = [
    [-1.0,  0.0,  0.0],  # F
    [ 0.0,  0.0,  0.0],  # C1
    [ 1.54, 0.0,  0.0],  # C2
    [ 3.08, 0.0,  0.0],  # C3
    [ 0.0,  1.1,  0.0],  # H1 (на C1)
    [ 0.0,  0.0,  1.1],  # H2 (на C1)
    [ 1.54, 1.1,  0.0],  # H3 (на C2)
    [ 1.54, 0.0,  1.1],  # H4 (на C2)
    [ 3.08, 1.1,  0.0],  # H5 (на C3)
    [ 3.08, 0.0,  1.1],  # H6 (на C3)
    [ 3.08, -0.8, -0.6]  # H7 (на C3)
]


coords = np.array(atoms)

distances = np.linalg.norm(coords[:, np.newaxis, :] - coords[np.newaxis, :, :], axis=2)


adjacency = (distances <= 1.6).astype(int)


np.fill_diagonal(adjacency, 0)

print("Матрица смежности для 1-фторпропана:")
print(adjacency)

[[-1.    0.    0.  ]
 [ 0.    0.    0.  ]
 [ 1.54  0.    0.  ]
 [ 3.08  0.    0.  ]
 [ 0.    1.1   0.  ]
 [ 0.    0.    1.1 ]
 [ 1.54  1.1   0.  ]
 [ 1.54  0.    1.1 ]
 [ 3.08  1.1   0.  ]
 [ 3.08  0.    1.1 ]
 [ 3.08 -0.8  -0.6 ]]
Матрица смежности для 1-фторпропана:
[[0 1 0 0 1 1 0 0 0 0 0]
 [1 0 1 0 1 1 0 0 0 0 0]
 [0 1 0 1 0 0 1 1 0 0 0]
 [0 0 1 0 0 0 0 0 1 1 1]
 [1 1 0 0 0 1 1 0 0 0 0]
 [1 1 0 0 1 0 0 1 0 0 0]
 [0 0 1 0 1 0 0 1 1 0 0]
 [0 0 1 0 0 1 1 0 0 1 0]
 [0 0 0 1 0 0 1 0 0 1 0]
 [0 0 0 1 0 0 0 1 1 0 0]
 [0 0 0 1 0 0 0 0 0 0 0]]


#### <p style='text-align: justify;'>4. В <i>модифицированной</i> матрице смежности на главной диагонали находится порядковый номер элемента $i$-го атома. Считайте из файла `share/1-Fluoropropane.xyz` в массив `atoms` симолы элементов для 1-фторпропана (в этом случае, в функции `np.loadtxt()` нужно явно указать тип данных) и, используя список `elements`, постройте и выведите на печать модифицированную матрицу смежности и сохраните её в файл `adjacency.txt`.

In [6]:
elements = ['H', 'He', 
            'Be', 'Li', 'B',  'C',  'N', 'O', 'F',  'Ne', 
            'Na', 'Mg', 'Al', 'Si', 'P', 'S', 'Cl', 'Ar']
atoms = np.loadtxt('share/1-Fluoropropane.xyz', dtype=str, skiprows=2, usecols=(0))
b = np.zeros((N, N), int)
for i in range(N):
    for j in range(N):
        if elements[i] == atoms[j]:
            atoms[j] = i + 1
            
for i in range(N):
    for j in range(N):
        if 0 < dist(coords[i], coords[j]) <=1.6:
            b[i][j] = 1

for i in range(N):
    b[i, i] = atoms[i]

print(b)


[[6 1 0 0 1 1 0 0 0 0 0]
 [1 6 1 0 1 1 0 0 0 0 0]
 [0 1 6 1 0 0 1 1 0 0 0]
 [0 0 1 9 0 0 0 0 1 1 1]
 [1 1 0 0 1 1 1 0 0 0 0]
 [1 1 0 0 1 1 0 1 0 0 0]
 [0 0 1 0 1 0 1 1 1 0 0]
 [0 0 1 0 0 1 1 1 0 1 0]
 [0 0 0 1 0 0 1 0 1 1 0]
 [0 0 0 1 0 0 0 1 1 1 0]
 [0 0 0 1 0 0 0 0 0 0 1]]


#### <p style='text-align: justify;'>5*. Магический квадрат — квадрат $N \times N$, содержащий числа от $1$ до $N^2$, при этом, сумма чисел в каждой строке, каждом столбце и на главных диагоналях одинакова. Алгоритм построения магического квадрата для нечётного $N$ можект быть следующим:
1. Начните с середины верхней строки, и присвойте $n = 1$.
2. Поместите $n$ в текущую позицию.
3. Если $n = N^2$, то квадрат полностью заполнен. Иначе увеличьте $n$ на $1$.
4. Переместитесь по диагонали вверх и вправо. Если вы вышли за границу сетки, продолжите с противоположной стороны. Если эта ячейка занята, то вместо неё переместитесь на одну ячейку вниз.
5. Вернитесь к шагу 2.
#### Напишите программу, которая запрашивает у пользователя $N$ (нечётное) и выводит массив $N \times N$, содержащий магический квадрат.

In [14]:
def magic_square(N):
    if N % 2 == 0:
        raise ValueError("N должно быть нечётным")
    
    square = np.zeros((N, N), int)
    
    row, col = 0, N // 2
    
    for n in range(1, N*N + 1):
        square[row][col] = n
        
        new_row = (row - 1) % N  
        new_col = (col + 1) % N  

        if square[new_row][new_col] != 0:
            row = (row + 1) % N 
            col = col             
        else:
            row, col = new_row, new_col  
    
    return square

#### <p style='text-align: justify;'>Проверьте, что массив, созданный в предыдущем задании, является магическим квадратом: выведите суммы чисел в каждой строке, каждом столбце и на главной диагонали.<br>Выведите сумму чисел на диагонали, идущей из верхнего правого в левый нижний угол матрицы.

In [16]:
if __name__ == "__main__":
    N = int(input("Введите нечётное N: "))
    if N % 2 == 0:
        print("Ошибка: N должно быть нечётным.")
    else:
        result = magic_square(N)1
        print("Суммы по столбцам:   ", result.sum(axis=0).tolist())
        print("Сумма главной диагонали:    ", result.diagonal().sum())
        print("Сумма побочной диагонали:   ", np.fliplr(result).diagonal().sum())


[[122 139 156 173 190 207 224   1  18  35  52  69  86 103 120]
 [138 155 172 189 206 223  15  17  34  51  68  85 102 119 121]
 [154 171 188 205 222  14  16  33  50  67  84 101 118 135 137]
 [170 187 204 221  13  30  32  49  66  83 100 117 134 136 153]
 [186 203 220  12  29  31  48  65  82  99 116 133 150 152 169]
 [202 219  11  28  45  47  64  81  98 115 132 149 151 168 185]
 [218  10  27  44  46  63  80  97 114 131 148 165 167 184 201]
 [  9  26  43  60  62  79  96 113 130 147 164 166 183 200 217]
 [ 25  42  59  61  78  95 112 129 146 163 180 182 199 216   8]
 [ 41  58  75  77  94 111 128 145 162 179 181 198 215   7  24]
 [ 57  74  76  93 110 127 144 161 178 195 197 214   6  23  40]
 [ 73  90  92 109 126 143 160 177 194 196 213   5  22  39  56]
 [ 89  91 108 125 142 159 176 193 210 212   4  21  38  55  72]
 [105 107 124 141 158 175 192 209 211   3  20  37  54  71  88]
 [106 123 140 157 174 191 208 225   2  19  36  53  70  87 104]]

Проверка ожидается 1695:
Суммы по строкам:    [1695, 