# Практикум по библиотеке NumPy

#### 1. Импортируйте библиотеку numpy под псевдонимом `np` (★☆☆)

In [4]:
import numpy as np

#### Создайте вектор (одномерный массив) `X` из 10 элементов равных $0.0$ (★☆☆)

In [2]:
x = np.zeros(10, float) 
print (x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Вычислите объём памяти (в байтах), необходимый для хранения элементов массива `X` (★☆☆)

In [3]:
memory_size = x.nbytes
print("Объём памяти (байты):", memory_size)

Объём памяти (байты): 80


#### Присвойте пятому по счёту элементу вектора `X` значение $5.0$ (★☆☆)

In [4]:
x[4] = 5.0  
print(x)

[0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]


#### 2. Создайте вектор `Y`, содержащий целые числа от 10 до 49 с шагом 1 (★☆☆)

In [5]:
Y = np.arange(10, 50)

print(Y)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### Поменяйте порядок элементов вектора `Y` на обратный (★☆☆)

In [6]:

Y = Y[::-1]

print(Y)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### Создайте матрицу `A` размером $3\times 3$, содержащую числа от $0$ до $8$ (★☆☆)
<center><img src="https://lk.challenges2024.ru/visualization/np_prac01.png" width=7.5%></center>

In [7]:

A = np.arange(9).reshape(3, 3)

print(A)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Создайте массив из списка `[1, 2, 0, 0, 4, 0]` и найдите в нём индексы ненулевых элементов(★☆☆)

In [8]:

arr = np.array([1, 2, 0, 0, 4, 0])

nonzero_indices = np.where(arr != 0)[0]

print("Массив:", arr)
print("Индексы ненулевых элементов:", nonzero_indices)


Массив: [1 2 0 0 4 0]
Индексы ненулевых элементов: [0 1 4]


#### 3. Создайте единичную матрицу `E` размера $5\times 5$ (★☆☆)

In [ ]:

E = np.eye(5)

print(E)


#### Создайте трёхмерный массив `T` размера $3\times 3\times 3$, содержащий случайные числа от $0.0$ до $1.0$ (★☆☆)

In [9]:
t = np.random.rand(3, 3, 3)
print(t)

[[[0.24724743 0.497762   0.44736503]
  [0.42596954 0.91447619 0.77120012]
  [0.88394461 0.33497608 0.35677879]]

 [[0.53767477 0.07360359 0.41394935]
  [0.58675613 0.39392278 0.34577011]
  [0.5579729  0.2149655  0.43914122]]

 [[0.48372495 0.87401948 0.16688057]
  [0.54197184 0.51807836 0.59687984]
  [0.38145744 0.69607549 0.56329532]]]


#### Найдите в массиве `T` минимальное, максимальное и среднее значения (★☆☆)

In [10]:
a = np.min(t)
b = np.max(t)
print(a, b)

0.07360359374839642 0.9144761852402707


#### Познакомьтесь с константами `np.nan` и `np.inf`. Проанализируйте результаты вычислений следующих выражений (★☆☆)

In [11]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))

nan
False
False
nan
True


#### 4. Создайте двумерный массив `B` размером $8\times 8$, содержащий $1.0$ на границах и $0.0$ в остальных элементах (★☆☆)
<center><img src="https://lk.challenges2024.ru/visualization/np_prac02.png" width=20%></center>

In [3]:
B = np.ones((8, 8))

B[1:-1, 1:-1] = 0

print(B)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


#### Добавьте границу (заполненную нулями) к существующему массиву `B` (★☆☆)
<center><img src="https://lk.challenges2024.ru/visualization/np_prac03.png" width=25%></center>

In [4]:
R = np.zeros((10,10))
R[1:9, 1:9] = B
print(R)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### Создайте матрицу `A` размером $5\times 5$, содержащую значения: $a_{2,1}=1$, $a_{3,2}=2$, $a_{4,3}=3$, $a_{5,4}=4$ , остальные — нули (★☆☆)
<center><img src="https://lk.challenges2024.ru/visualization/np_prac04.png" width=12.5%></center>

In [6]:
A = np.diag([1, 2, 3, 4], k=1)

print(A)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


#### Создайте матрицу `B` размером $5\times 5$, заполненную $0$ и $1$ в шахматном порядке (на главной диагонали — $1$) (★☆☆)
<center><img src="https://lk.challenges2024.ru/visualization/np_prac05.png" width=12.5%></center>

In [8]:
B = np.arange(1,26).reshape(5,5)
B %= 2
print(B)

[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]


#### Найдите матричное произведение `A` и `B` (★☆☆)

In [9]:
print(A@B)

[[0 1 0 1 0]
 [2 0 2 0 2]
 [0 3 0 3 0]
 [4 0 4 0 4]
 [0 0 0 0 0]]


#### 5*. Создайте вектор `X`, содержащий 10 значений, равномерно распределённых на отрезке $(0,1)$, не включающий концы отрезка (★☆☆)
<center><img src="https://lk.challenges2024.ru/visualization/np_prac06.png" width=25%></center>

In [10]:
X = np.linspace(0, 1, 12)[1:-1]
print(X)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### У элементов вектора `X`, имеющих значения от $0.3$ до $0.7$, поменяйте знак на противоположный. (★☆☆)

In [11]:
X[(0.3 < X) & (X < 0.7)] *= -1
print(X)

[ 0.09090909  0.18181818  0.27272727 -0.36363636 -0.45454545 -0.54545455
 -0.63636364  0.72727273  0.81818182  0.90909091]


#### Создайте вектор `X`, содержащий 10 случайных значений из интервала $(0,1)$ и измените максимальное значение на $0$. (★☆☆)

In [12]:
X = np.random.rand(10)
print (X)
X[X.argmax()] = 0
print(X)

[0.50290301 0.04915594 0.88699883 0.74251368 0.42005733 0.32238744
 0.72653324 0.0822404  0.51406518 0.2934118 ]
[0.50290301 0.04915594 0.         0.74251368 0.42005733 0.32238744
 0.72653324 0.0822404  0.51406518 0.2934118 ]


#### Выведите значение вектора `X`, ближайшее к $0.5$. (★☆☆)

In [13]:
print(X[np.abs(X - 0.5).argmin()])

0.5029030146687293


#### Распечатайте диапазон значений стандартных числовых типов данных в Numpy. (★☆☆)

In [14]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16
