# Практикум по библиотеке NumPy

**ЧТОБЫ ВАША ПРОГРАММА РАБОТАЛА КОРРЕКТНО НЕОБХОДИМО В КАЖДУЮ ЯЧЕЙКУ ВПИСАТЬ**
```python
import numpy as np
```
**ЛИБО СДЕЛАТЬ ЭТО ОДИН РАЗ И НЕ ОСТАНАВЛИВАТЬ КЕРНЕР, ИНАЧЕ НЕ БУДЕТ РАБОТАТЬ**

#### 1. Импортируйте библиотеку numpy под псевдонимом `np` 

In [1]:
import numpy as np

#### 2. Напечатайте версию numpy и настройки конфигурации 

In [2]:

print(np.__version__)
np.show_config()

2.1.1
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.10.14/lib/python3.10/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.10.14/lib/python3.10/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.10.14/lib/python3.10/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.10.14/lib/python3.10/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.

#### 3. Создайте вектор (одномерный массив) `Z` из 10 элементов равных нулю

In [3]:
z = np.zeros(10, float)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  Вычислите объём памяти (в байтах), необходимый для хранения элементов массива `Z`

In [4]:
print(z.size * z.itemsize)

80


#### 5.  Выведите на печать документацию по функции `add` библиотеки numpy 

In [5]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6.  Присвойте пятому элементу вектора `Z` значение 1.0

In [6]:
z[4]=1.0
print(z)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Создайте вектор `Z`, содержащий числа от 10 до 49 с шагом 1

In [7]:
Z = np.arange(10, 50, 1)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Поменяйте порядок элементов вектора `Z`  на обратный 

In [8]:
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Создайте матрицу `A` размером 3x3, содержащую числа от 0 до 8 

In [9]:
A = np.linspace(0, 8, 9)
A = A.reshape(3, 3)
print(A)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


#### 10. Найдите индексы ненулевых элементов из  \[1,2,0,0,4,0\] 

In [10]:
b = np.array([1,2,0,0,4,0])
print(np.where(b != 0))

(array([0, 1, 4]),)


#### 11. Создайте единичную матрицу `E` размера 5x5 

In [11]:
e = np.eye(5, 5)
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### 12. Создайте трёхмерный массив `T` размера 3x3x3, содержащий случайные числа от 0 до 1 

In [12]:
t = np.random.rand(3, 3, 3)
print(t)

[[[0.26091487 0.80665452 0.38973259]
  [0.00929342 0.21373644 0.96931796]
  [0.89315452 0.38075002 0.03874135]]

 [[0.46492451 0.02793227 0.62289175]
  [0.17378151 0.32584759 0.94719745]
  [0.65719293 0.00452849 0.22114904]]

 [[0.13816475 0.55212223 0.57887994]
  [0.73139827 0.006068   0.63580798]
  [0.60958148 0.50580568 0.42276979]]]


#### 13. Найдите в массиве `T` минимальное и максимальное значения 

In [13]:
a = np.min(t)
b = np.max(t)
print(a, b)

0.004528487603740694 0.9693179602659426


#### 14. Найдите в массиве `T` среднее значение 

In [14]:
print(t.mean())

0.4291977519738821


#### 15. Создайте двумерный массив `B` размером 8x8, содержащий 1.0 на границах  и  0.0 

In [15]:
B = np.zeros((8,8,))
B[0,:] = 1.0
B[:,7] = 1.0
B[:,0] = 1.0
B[7,:] = 1.0
print(B)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. Добавьте границу (заполненную нулями) к существующему массиву `B`

In [16]:
R = np.zeros((10,10))
R[1:9, 1:9] = B
print(R)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. Проанализируйте результаты вычислений следующих выражений 

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Создайте матрицу `A` размером 5x5, содержащую значения: $a_{2,1}=1$, $a_{3,2}=2$, $a_{4,3}=3$, $a_{5,4}=4$ , остальные — нули 

In [18]:
A = np.zeros((5,5))
A[1][0]=1
A[2][1]=2
A[3][2]=3
A[4][3]=4
print(A)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Создайте матрицу `B` размером 5x5, заполненную 0 и 1 в шахматном порядке (на главной диагонали — единицы) 

In [19]:
B = np.arange(1,26).reshape(5,5)
B %= 2
print(B)

[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]


#### 20. Найдите матричное произведение `A` и `B` 

In [20]:
print(A @ B)

[[0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1.]
 [0. 2. 0. 2. 0.]
 [3. 0. 3. 0. 3.]
 [0. 4. 0. 4. 0.]]


#### 21. Создайте вектор `X`, содержащий 10 значений, равномерно распределённых на отрезке $(0,1)$, не включающий концы отрезка. 

In [21]:
X = np.linspace(0, 1, 12)[1:-1]
print(X)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 22. У элементов вектора `X`, имеющих значения от 0.3 до 0.7, поменяйте знак на противоположный. 

In [22]:
X[(0.3 < X) & (X < 0.7)] *= -1
print(X)

[ 0.09090909  0.18181818  0.27272727 -0.36363636 -0.45454545 -0.54545455
 -0.63636364  0.72727273  0.81818182  0.90909091]


#### 23. Создайте вектор `X`, содержащий 10 случайных значений из интервала $(0,1)$ и измените максимальное значение на $0$.

In [23]:
X = np.random.rand(10)
X[X.argmax()] = 0
print(X)

[0.71476796 0.05369429 0.34382063 0.50599634 0.23690069 0.64309793
 0.25680693 0.17531262 0.         0.54576775]


#### 24. Выведите значение вектора `X`, ближайшее к $0.5$. 

In [24]:
print(X[np.abs(X - 0.5).argmin()])

0.5059963388966812


#### 25. Распечатайте диапазон значений стандартных числовых типов данных в Numpy. 

In [25]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16
